import type { Metadata } from "next";
import { Inter, League_Spartan } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";

const league_spartan = League_Spartan({
  subsets: ["latin"],
  weight: ["500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  applicationName: "Room Homepage",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${league_spartan.className} min-h-screen`}>
        <Header />
        {children}
        <div className="text-center p-9 mobile:text-xs laptop:text-base">
          Challenge by{" "}
          <a href="https://www.frontendmentor.io?ref=challenge" target="_blank">
            Frontend Mentor
          </a>
          . Coded by{" "}
          <a href="https://github.com/Rafael-Urei" target="_blank">
            Rafael de Souza
          </a>
          .
        </div>
      </body>
    </html>
  );
}
